
# Partition: CSECT001
Data_Names WSAVE = WSAVE
Data_Types WSAVE = FWORD_p
Data_Lengths WSAVE = 72
Data_Repeats WSAVE = 18
Data_Names WTOTAL = WTOTAL
Data_Types WTOTAL = DECIMAL
Data_Lengths WTOTAL = 5
Data_Names WPRT = WPRT
Data_Types WPRT = BYTE_p
Data_Lengths WPRT = 80
Data_Names WSPACES = WSPACES
Data_Types WSPACES = BYTE_p
Data_Lengths WSPACES = 80
Data_Names WREP1 = WREP1
Data_Types WREP1 = BYTE_p
Data_Lengths WREP1 = 14
Data_Names WREP2 = WREP2
Data_Types WREP2 = BYTE
Data_Lengths WREP2 = 1
Data_Names WREP3 = WREP3
Data_Types WREP3 = BYTE_p
Data_Lengths WREP3 = 20
Data_Names WREP4 = WREP4
Data_Types WREP4 = struct
Data_Lengths WREP4 = 80
Data_Names WXDAT1 = WREP4.WXDAT1
Data_Types WREP4.WXDAT1 = BYTE_p
Data_Lengths WREP4.WXDAT1 = 6
Data_Fields WREP4 0 6 = WXDAT1
Data_Names WXENT2 = WREP4.WXENT2
Data_Types WREP4.WXENT2 = struct
Data_Lengths WREP4.WXENT2 = 8
Data_Fields WREP4 8 8 = WXENT2
Data_Names WXDAT2 = WREP4.WXENT2.WXDAT2
Data_Types WREP4.WXENT2.WXDAT2 = BYTE_p
Data_Lengths WREP4.WXENT2.WXDAT2 = 6
Data_Fields WREP4.WXENT2 0 6 = WXDAT2
Data_Names WXDAT3 = WREP4.WXDAT3
Data_Types WREP4.WXDAT3 = BYTE_p
Data_Lengths WREP4.WXDAT3 = 6
Data_Fields WREP4 16 6 = WXDAT3
Data_Names WXDAT4 = WREP4.WXDAT4
Data_Types WREP4.WXDAT4 = BYTE_p
Data_Lengths WREP4.WXDAT4 = 6
Data_Fields WREP4 24 6 = WXDAT4
Data_Names WXDAT5 = WREP4.WXDAT5
Data_Types WREP4.WXDAT5 = BYTE_p
Data_Lengths WREP4.WXDAT5 = 6
Data_Fields WREP4 32 6 = WXDAT5
Data_Names WXDAT6 = WREP4.WXDAT6
Data_Types WREP4.WXDAT6 = BYTE_p
Data_Lengths WREP4.WXDAT6 = 6
Data_Fields WREP4 40 6 = WXDAT6
Data_Names WXDAT7 = WREP4.WXDAT7
Data_Types WREP4.WXDAT7 = BYTE_p
Data_Lengths WREP4.WXDAT7 = 6
Data_Fields WREP4 48 6 = WXDAT7
Data_Names WXDAT8 = WREP4.WXDAT8
Data_Types WREP4.WXDAT8 = BYTE_p
Data_Lengths WREP4.WXDAT8 = 6
Data_Fields WREP4 56 6 = WXDAT8
Data_Names WYAMT1 = WREP4.WYAMT1
Data_Types WREP4.WYAMT1 = DECIMAL
Data_Lengths WREP4.WYAMT1 = 4
Data_Fields WREP4 64 4 = WYAMT1
Data_Names WYRATE = WREP4.WYRATE
Data_Types WREP4.WYRATE = DECIMAL
Data_Lengths WREP4.WYRATE = 3
Data_Fields WREP4 68 3 = WYRATE
Data_Names WYAMT2 = WREP4.WYAMT2
Data_Types WREP4.WYAMT2 = DECIMAL
Data_Lengths WREP4.WYAMT2 = 4
Data_Fields WREP4 71 4 = WYAMT2
# End of file
