(set! *internal-c-functions* (append *internal-c-functions* '(
/foreach-/s/s/a-1
/foreach-/s/s/a-2
/foreach-/s/s/a-3
/foreach-abort_processing-1
/foreach-abort_processing-2
/foreach-abort_processing-3
/foreach-abort_processing-4
/foreach-abort_processing-5
/foreach-abort_processing-6
/foreach-abort_processing-7
/foreach-abort_processing-8
/foreach-absorb_left-1
/foreach-absorb_left-2
/foreach-absorb_right-1
/foreach-actions_to_procs-1
/foreach-actions_to_where-1
/foreach-actions_to_where-2
/foreach-actions_to_where-3
/foreach-actions_to_where-4
/foreach-add_loop_to_action-1

/foreach-all_proc_stacks_to_pars-1

/foreach-all_proc_stacks_to_pars-2

/foreach-all_push_pop-1
/foreach-all_push_pop-2
/foreach-all_push_pop-3
/foreach-array_to_vars-1
/foreach-array_to_vars-2
/foreach-array_to_vars-3
/foreach-array_to_vars-4
/foreach-blocks-1
/foreach-collapse_action_system-1

/foreach-collapse_action_system-2

/foreach-collapse_action_system-3

/foreach-collapse_action_system-4

/foreach-collapse_action_system-5

/foreach-collapse_action_system-6

/foreach-constant_propagation-1

/foreach-constant_propagation-10

/foreach-constant_propagation-11

/foreach-constant_propagation-12

/foreach-constant_propagation-13

/foreach-constant_propagation-14

/foreach-constant_propagation-15

/foreach-constant_propagation-16

/foreach-constant_propagation-17

/foreach-constant_propagation-18

/foreach-constant_propagation-19

/foreach-constant_propagation-2

/foreach-constant_propagation-20

/foreach-constant_propagation-21

/foreach-constant_propagation-22

/foreach-constant_propagation-23

/foreach-constant_propagation-24

/foreach-constant_propagation-25

/foreach-constant_propagation-26

/foreach-constant_propagation-27

/foreach-constant_propagation-28

/foreach-constant_propagation-29

/foreach-constant_propagation-3

/foreach-constant_propagation-30

/foreach-constant_propagation-31

/foreach-constant_propagation-32

/foreach-constant_propagation-33

/foreach-constant_propagation-34

/foreach-constant_propagation-35

/foreach-constant_propagation-36

/foreach-constant_propagation-37

/foreach-constant_propagation-38

/foreach-constant_propagation-39

/foreach-constant_propagation-4

/foreach-constant_propagation-5

/foreach-constant_propagation-6

/foreach-constant_propagation-7

/foreach-constant_propagation-8

/foreach-constant_propagation-9

/foreach-delete_all_assertions-1

/foreach-delete_all_comments-1

/foreach-delete_all_comments-2

/foreach-delete_all_comments-3

/foreach-delete_all_redundant-1

/foreach-delete_all_redundant-2

/foreach-delete_all_redundant-3

/foreach-delete_all_redundant-4

/foreach-delete_all_skips-1
/foreach-delete_redundant_regs-1

/foreach-delete_redundant_regs-2

/foreach-delete_redundant_regs-3

/foreach-delete_redundant_regs-4

/foreach-delete_redundant_regs-5

/foreach-delete_redundant_regs-6

/foreach-delete_redundant_regs-7

/foreach-delete_redundant_regs-8

/foreach-delete_unreachable_code-1

/foreach-delete_unreachable_code-2

/foreach-double_to_single_loop-1

/foreach-double_to_single_loop-2

/foreach-double_to_single_loop-3

/foreach-expand_call-1
/foreach-find_terminals-1
/foreach-fix_dispatch-1
/foreach-fix_dispatch-10
/foreach-fix_dispatch-11
/foreach-fix_dispatch-12
/foreach-fix_dispatch-13
/foreach-fix_dispatch-14
/foreach-fix_dispatch-15
/foreach-fix_dispatch-16
/foreach-fix_dispatch-17
/foreach-fix_dispatch-18
/foreach-fix_dispatch-19
/foreach-fix_dispatch-2
/foreach-fix_dispatch-20
/foreach-fix_dispatch-21
/foreach-fix_dispatch-22
/foreach-fix_dispatch-23
/foreach-fix_dispatch-24
/foreach-fix_dispatch-25
/foreach-fix_dispatch-26
/foreach-fix_dispatch-27
/foreach-fix_dispatch-28
/foreach-fix_dispatch-29
/foreach-fix_dispatch-3
/foreach-fix_dispatch-30
/foreach-fix_dispatch-31
/foreach-fix_dispatch-32
/foreach-fix_dispatch-33
/foreach-fix_dispatch-4
/foreach-fix_dispatch-5
/foreach-fix_dispatch-6
/foreach-fix_dispatch-7
/foreach-fix_dispatch-8
/foreach-fix_dispatch-9
/foreach-flag_removal-1
/foreach-flag_removal-10
/foreach-flag_removal-11
/foreach-flag_removal-12
/foreach-flag_removal-2
/foreach-flag_removal-3
/foreach-flag_removal-4
/foreach-flag_removal-5
/foreach-flag_removal-6
/foreach-flag_removal-7
/foreach-flag_removal-8
/foreach-flag_removal-9
/foreach-floop_to_while-1
/foreach-floop_to_while-10
/foreach-floop_to_while-11
/foreach-floop_to_while-12
/foreach-floop_to_while-2
/foreach-floop_to_while-3
/foreach-floop_to_while-4
/foreach-floop_to_while-5
/foreach-floop_to_while-6
/foreach-floop_to_while-7
/foreach-floop_to_while-8
/foreach-floop_to_while-9
/foreach-flowchart-1
/foreach-flowchart-2
/foreach-force_double_to_single_loop-1

/foreach-fully_absorb_right-1

/foreach-globals_to_pars-1
/foreach-invert-1
/foreach-join_all_cases-1
/foreach-join_all_cases-2
/foreach-loop_to_move-1
/foreach-make_proc-1
/foreach-make_proc-2
/foreach-make_proc-3
/foreach-make_proc-4
/foreach-make_proc-5
/foreach-make_reducible-1
/foreach-make_reducible-2
/foreach-maths-1
/foreach-maths-10
/foreach-maths-11
/foreach-maths-12
/foreach-maths-13
/foreach-maths-14
/foreach-maths-15
/foreach-maths-16
/foreach-maths-17
/foreach-maths-18
/foreach-maths-19
/foreach-maths-2
/foreach-maths-20
/foreach-maths-21
/foreach-maths-22
/foreach-maths-23
/foreach-maths-24
/foreach-maths-25
/foreach-maths-26
/foreach-maths-27
/foreach-maths-28
/foreach-maths-29
/foreach-maths-3
/foreach-maths-30
/foreach-maths-4
/foreach-maths-5
/foreach-maths-6
/foreach-maths-7
/foreach-maths-8
/foreach-maths-9
/foreach-maths2-2-1
/foreach-maths2-2-2
/foreach-merge_calls_in_action-1

/foreach-merge_calls_in_action-2

/foreach-merge_calls_in_action-3

/foreach-merge_calls_in_action-4

/foreach-merge_calls_in_action-5

/foreach-merge_calls_in_system-1

/foreach-merge_calls_in_system-2

/foreach-merge_calls_in_system-3

/foreach-merge_calls_in_system-4

/foreach-merge_calls_in_system-5

/foreach-merge_calls_in_system-6

/foreach-merge_calls_in_system-7

/foreach-meta_trans-1
/foreach-metrics-1
/foreach-metrics-2
/foreach-metrics-3
/foreach-move_to_right-1
/foreach-move_to_right-2
/foreach-move_to_right-3
/foreach-move_to_right-4
/foreach-move_to_right-5
/foreach-move_to_right-6
/foreach-move_to_right-7
/foreach-move_to_right-8
/foreach-proc_to_funct-1
/foreach-prune_dispatch-1
/foreach-prune_dispatch-2
/foreach-prune_dispatch-3
/foreach-prune_dispatch-4
/foreach-prune_dispatch-5
/foreach-push_pop-1
/foreach-query-1
/foreach-query-2
/foreach-recursion_to_loop-1

/foreach-recursion_to_loop-2

/foreach-recursion_to_loop-3

/foreach-recursion_to_loop-4

/foreach-refine_spec-1
/foreach-refine_spec-2
/foreach-remove_all_redundant_vars-1

/foreach-remove_all_redundant_vars-2

/foreach-remove_dummy_loop-1

/foreach-remove_dummy_loop-2

/foreach-remove_redundant_vars-1

/foreach-remove_redundant_vars-10

/foreach-remove_redundant_vars-11

/foreach-remove_redundant_vars-12

/foreach-remove_redundant_vars-2

/foreach-remove_redundant_vars-3

/foreach-remove_redundant_vars-4

/foreach-remove_redundant_vars-5

/foreach-remove_redundant_vars-6

/foreach-remove_redundant_vars-7

/foreach-remove_redundant_vars-8

/foreach-remove_redundant_vars-9

/foreach-rename_defns-1
/foreach-rename_local_vars-1

/foreach-rename_local_vars-2

/foreach-rename_local_vars-3

/foreach-rename_proc-1
/foreach-rename_proc-2
/foreach-rename_proc-3
/foreach-replace_with_value-1

/foreach-replace_with_value-2

/foreach-restore_local_vars-1

/foreach-semantic_slice-1
/foreach-semantic_slice-2
/foreach-semantic_slice-3
/foreach-semantic_slice-4
/foreach-semantic_slice-5
/foreach-semantic_slice-6
/foreach-semantic_slice-7
/foreach-semantic_slice-8
/foreach-separate_exit_code-1

/foreach-separate_exit_code-2

/foreach-separate_exit_code-3

/foreach-separate_right-1
/foreach-separate_right-2
/foreach-separate_right-3
/foreach-simple_slice-1
/foreach-simple_slice-2
/foreach-simplify-1
/foreach-simplify_action_system-1

/foreach-simplify_action_system-2

/foreach-simplify_action_system-3

/foreach-simplify_action_system-4

/foreach-simplify_action_system-5

/foreach-simplify_action_system-6

/foreach-simplify_action_system-7

/foreach-simplify_action_system-8

/foreach-simplify_item-1
/foreach-simplify_item-2
/foreach-simplify_item-3
/foreach-simplify_item-4
/foreach-sort_procs-1
/foreach-stack_to_par-1
/foreach-stack_to_par-2
/foreach-stack_to_return-1
/foreach-stack_to_return-2
/foreach-stack_to_return-3
/foreach-stack_to_return-4
/foreach-stack_to_return-5
/foreach-stack_to_return-6
/foreach-stack_to_return-7
/foreach-stack_to_return-8
/foreach-static_single_assignment-1

/foreach-static_single_assignment-2

/foreach-substitute_and_delete-1

/foreach-substitute_and_delete-2

/foreach-summ2-1
/foreach-summ2-2
/foreach-summ2-3
/foreach-syntactic_slice-1
/foreach-syntactic_slice-10
/foreach-syntactic_slice-11
/foreach-syntactic_slice-12
/foreach-syntactic_slice-13
/foreach-syntactic_slice-2
/foreach-syntactic_slice-3
/foreach-syntactic_slice-4
/foreach-syntactic_slice-5
/foreach-syntactic_slice-6
/foreach-syntactic_slice-7
/foreach-syntactic_slice-8
/foreach-syntactic_slice-9
/foreach-take_out_of_loop-1
/foreach-take_out_of_loop-2
/foreach-unfold_proc_calls-1

/foreach-unfold_proc_calls-2

/foreach-unfold_proc_calls-3

/foreach-unfold_proc_calls-4

/foreach-unroll_loop-1
/foreach-var_pars_to_val_pars-1

/foreach-while_to_reduce-1
/foreach-wp-1
/foreach-wp-2
/foreach-wp-3
/foreach-wp-4
/foreach-wp-5
/foreach-wsl2scheme-1
/foreach-wsl2scheme-10
/foreach-wsl2scheme-11
/foreach-wsl2scheme-12
/foreach-wsl2scheme-13
/foreach-wsl2scheme-14
/foreach-wsl2scheme-15
/foreach-wsl2scheme-16
/foreach-wsl2scheme-17
/foreach-wsl2scheme-2
/foreach-wsl2scheme-3
/foreach-wsl2scheme-4
/foreach-wsl2scheme-5
/foreach-wsl2scheme-6
/foreach-wsl2scheme-7
/foreach-wsl2scheme-8
/foreach-wsl2scheme-9
@a_proc_calls
@abort_processing_code
@abort_processing_test
@absorb_left_code
@absorb_left_code_assignment
@absorb_left_fix_vars
@absorb_left_test
@absorb_left_test_assignment
@absorb_left_test_cond
@absorb_left_test_floop
@absorb_left_test_for
@absorb_left_test_var
@absorb_left_test_where
@absorb_left_test_while
@absorb_right_code
@absorb_right_code2
@absorb_right_test
@action_distances
@actions_to_procs_code
@actions_to_procs_test
@actions_to_where_code
@actions_to_where_test
@add_assertion_code
@add_assertion_test
@add_left_code
@add_left_test
@add_loop_to_action_code
@add_loop_to_action_test
@align_nested_statements_code
@align_nested_statements_test
@align_nested_vars_code
@align_nested_vars_test
@all_hex?
@all_pattern_type?
@all_proc_stacks_to_pars_code
@all_proc_stacks_to_pars_test
@all_push_pop_code
@all_push_pop_test
@all_tail_recursive?
@all_variables
@all_vars
@and
@any_call_in_var?
@any_int_type?
@any_pattern_type?
@any_prefix_in?
@any_tail_recursive?
@any_var_type?
@ap_abort
@apply_to_right_code
@apply_to_right_test
@apply_to_right_test_cond
@apply_to_right_test_d_do
@array_to_vars_code
@array_to_vars_test
@as_type
@as_type_gen
@assd_only
@assd_to_self
@assigned
@assignment_stats
@assoc
@ateach_cond
@ateach_expn
@ateach_gen
@ateach_global_var
@ateach_lvalue
@ateach_non_action_statement

@ateach_s

@ateach_statement
@ateach_stats
@ateach_terminal
@ateach_terminal_stats

@ateach_var

@ateach_variable
@atp_dispatch_calls
@atp_procable?
@atp_sad
@av_find_called
@av_process_statements
@av_test_statements
@aw_make_recursive
@basic_blocks
@bb_a_s
@bb_abort
@bb_block
@bb_call
@bb_cond
@bb_d_do
@bb_exit
@bb_fermat_comment
@bb_floop
@bb_for
@bb_get_node
@bb_list
@bb_make_assign
@bb_name
@bb_node
@bb_proc
@bb_proc_call
@bb_statements
@bb_var
@bb_where
@bb_while
@bb_write_assign
@bb_write_block
@bb_write_comments
@bb_write_item
@bb_write_list
@bb_write_node_line
@big_proc
@bin_to_hex
@bit_op
@bl_metric
@breadth_first_search
@bubble_sort
@bubble_sort1
@budget
@buffer
@byte
@c_make
@call_freq
@call_graph
@called?
@calls
@cas_unfold_least_called_action

@cfdf_metric
@char_in_str?
@check_globals_in_defns?
@checkpoint
@clear_state
@clever_delete
@clobbered
@close_input_port
@close_output_port
@collapse_action_system_code
@collapse_action_system_new1
@collapse_action_system_new1_orig
@collapse_action_system_new2
@collapse_action_system_simple
@collapse_action_system_test
@collapse_all_systems_code
@collapse_all_systems_test
@combine_wheres_code
@combine_wheres_test
@command_list
@comp_tc
@components
@components?
@constant_propagation_code
@constant_propagation_test
@count_proc_defns
@cp_a_proc
@cp_a_s
@cp_a_s_reg
@cp_abort
@cp_action
@cp_actions
@cp_all_but
@cp_all_numbers?
@cp_assert
@cp_assert_condition
@cp_assignment
@cp_assigns
@cp_assigns_sub
@cp_call
@cp_cc_check
@cp_cc_cond

@cp_cc_set

@cp_cc_statements

@cp_check_equiv

@cp_clobber
@cp_clobber_broke
@cp_clobber_list
@cp_clobber_value
@cp_clobber_zeros
@cp_cond
@cp_constant?
@cp_constant_?
@cp_constant_dsect_pointers
@cp_cycle2
@cp_cycle?
@cp_d_do
@cp_d_if
@cp_decrement_l
@cp_definition
@cp_definitions
@cp_deny_condition
@cp_do_assigns
@cp_exit
@cp_exit_sub
@cp_find_dispatch_codes
@cp_find_dsects
@cp_find_return_elts
@cp_first_time_flag
@cp_fix_cc_conds

@cp_floop
@cp_for
@cp_for_in
@cp_gen_loop
@cp_generic
@cp_get
@cp_guarded
@cp_in?
@cp_increment_l
@cp_init_dsect_pointers

@cp_make_proc_call
@cp_make_seq
@cp_maybe_absorb_left
@cp_maybe_expand
@cp_maybe_expand_cc
@cp_memory_address_fix
@cp_merge
@cp_merge_keep
@cp_mergel
@cp_minus_v
@cp_multi_valued_vars
@cp_multiple_destinations
@cp_once_called_codes
@cp_parameterless_proc_body
@cp_pop
@cp_pop_regs
@cp_print_l
@cp_proc_body
@cp_proc_call
@cp_push
@cp_push_regs
@cp_put
@cp_put0
@cp_put0_if_safe
@cp_put_if_safe
@cp_reg_init_var?
@cp_rel_seg_lvalue
@cp_remove
@cp_remove_sub
@cp_replace_cc0
@cp_replace_cc3
@cp_restore_state
@cp_save_state
@cp_scan_for_return_code

@cp_simple_cc0
@cp_simple_cc3
@cp_skip
@cp_spec
@cp_statement
@cp_statements
@cp_sub_seg_lvalue
@cp_summary
@cp_trim_exit_code
@cp_unfold_dispatch

@cp_update
@cp_update_entries

@cp_var
@cp_var_name
@cp_variable?
@cp_where
@cp_while
@cp_x_proc
@crp_array
@crp_cond
@crp_conds
@crp_expn
@crp_expns
@crp_item
@crp_lvalue
@crp_lvalues
@crp_name
@crp_stat
@crp_var
@cs
@cs?
@cut
@cut_rest
@d_do_to_floop_code
@d_do_to_floop_test
@data
@decrement_statement_code
@decrement_statement_test
@delete
@delete_all_assertions_code
@delete_all_assertions_test
@delete_all_comments_code
@delete_all_comments_test
@delete_all_redundant_code
@delete_all_redundant_test
@delete_all_skips_code
@delete_all_skips_test
@delete_file
@delete_item_code
@delete_item_test
@delete_nth
@delete_redundant_regs_code
@delete_redundant_regs_test
@delete_redundant_statement_code
@delete_redundant_statement_test
@delete_rest
@delete_unreachable_cases
@delete_unreachable_code_code
@delete_unreachable_code_test
@delete_what_follows_code
@delete_what_follows_test
@depth
@digit?
@digits?
@do_match
@do_match_any

@do_match_list
@do_match_many

@do_match_sequence

@double_to_single_loop_code
@double_to_single_loop_test
@down
@down?
@down_last
@down_to
@dpq2_sort
@dpq_pivots
@dpq_sort
@dpq_sort_iter
@dpq_sort_opt
@dpq_sort_rec
@dpq_sort_rec_dumb_pivot
@dpq_sort_rec_mine
@dpq_sort_test
@drs_fix_procs
@drs_get
@drs_process
@drs_process_comps

@drs_put
@drs_restore_procs
@drs_scan_ok?
@dsect_clash?
@dtable_get
@dtable_put
@dtable_value_part
@edit
@edit_parent
@effective_size
@either_prefix?
@elements
@else_if_to_elsif_code
@else_if_to_elsif_test
@elsif_to_else_if_code
@elsif_to_else_if_test
@elt_clash?
@elt_clash_list?
@elt_lvars
@elt_remove
@elt_remove_fields
@elt_strip_a
@elt_strip_dsect
@elt_subtract
@elt_to_expn
@elt_to_lvalue
@elt_to_string
@elts_addr
@elts_assd_to_self
@elts_assigned
@elts_redefined
@elts_uba
@elts_used
@end_edit
@end_write
@ends_with?
@ends_with_underscore_digits?
@entire_loop_unroll
@eof?
@eol?
@equal?
@equal_items?
@equal_x_comments?
@esm
@essential
@exits_terminal?
@expand_and_separate_all_code
@expand_and_separate_all_test
@expand_and_separate_code
@expand_and_separate_test
@expand_call_code
@expand_call_test
@expand_forward_code
@expand_forward_test
@expand_funct_calls
@expand_proc_calls
@expn_to_lvalue
@expn_to_var
@expn_to_var_list
@expn_to_var_type
@fail
@fail_message
@failed?
@false?
@fc_a_s
@fc_abort
@fc_action
@fc_actions
@fc_append
@fc_block
@fc_block_ok?
@fc_call
@fc_code
@fc_comments
@fc_cond
@fc_d_if
@fc_definition
@fc_definitions
@fc_dispatch
@fc_edge
@fc_edge2
@fc_end_subgraph
@fc_end_subgraph_
@fc_entry_point?
@fc_exit
@fc_finalise
@fc_floop
@fc_for
@fc_force_to_end
@fc_force_to_end_
@fc_generic
@fc_guarded
@fc_guarded_list
@fc_guardeds
@fc_initialise
@fc_multi_block
@fc_node
@fc_protect
@fc_start_subgraph
@fc_start_subgraph_
@fc_statement
@fc_statement_list
@fc_statements
@fc_test

@fc_var
@fc_where
@fc_while
@fd_action

@fd_bit_or_code_check
@fd_check_return_code_inc
@fd_clobber_value
@fd_find_call
@fd_inc_return_code

@fd_init

@fd_is_code?
@fd_jump_table_fix
@fd_jump_table_fix2

@fd_main
@fd_move_to_assignment
@fd_once_called_subroutines

@fd_process_simple_proc

@fd_rebuild_as

@fd_remove_ext_calls

@fd_rename_dsect_code_stores

@fd_restore_dsect_code_stores
@fd_separate_dispatch_calls
@fd_succs_and_preds

@fd_unfold_dispatch

@fd_unfold_start_action

@fd_update_addr_vars

@fib
@file_exists?
@fill_type?
@final_seg
@find_dispatch_codes
@find_index_vars
@find_statement
@find_terminals_code
@find_terminals_test
@find_type
@find_value
@find_variable
@fix_cond
@fix_cond_guards
@fix_cond_item
@fix_dijkstra
@fix_dijkstra_item
@fix_dispatch_code
@fix_dispatch_test
@fix_item
@fix_quotes
@fixup
@fixup_cond
@fixup_statement
@flag_removal_code
@flag_removal_test
@floop_to_while_code
@floop_to_while_complex
@floop_to_while_convert
@floop_to_while_invert
@floop_to_while_main1
@floop_to_while_main1a
@floop_to_while_main2
@floop_to_while_sub
@floop_to_while_test
@flowchart
@for_in_to_reduce_code
@for_in_to_reduce_test
@for_to_while_code
@for_to_while_test
@force_double_to_single_loop_code
@force_double_to_single_loop_test
@foreach_cond
@foreach_expn
@foreach_gen
@foreach_gen_s

@foreach_global_var
@foreach_lvalue
@foreach_non_action_statement

@foreach_s

@foreach_statement
@foreach_stats
@foreach_terminal
@foreach_terminal_stats

@foreach_variable
@foreach_vars

@format
@fr_check_for_flags
@fr_check_for_flags_orig
@fr_entire_loop_flag

@fr_find_values
@fr_get_values
@fr_loop_flag
@fr_preprocess_flags
@fr_process1

@fr_reduce_par2

@fr_reduce_pars
@fr_replace
@ft_process
@full_assd_only
@full_assd_to_self
@full_assigned
@full_redefined
@full_uba
@full_used
@full_used_only
@full_variables
@full_vars
@fully_absorb_right_code
@fully_absorb_right_test
@fully_expand_forward_code
@fully_expand_forward_test
@funct_call_freq
@funct_called?
@funct_calls
@fv_self_assign
@gcr_cond_fix
@gen_can_reduce?
@gen_do_rdc?
@gen_dummy?
@gen_expand_forward
@gen_improper?
@gen_less?
@gen_less_lists?
@gen_proper?
@gen_reachable?
@gen_reducible?
@gen_terminal?
@gen_tvs
@gen_type
@gen_type_count
@get
@get_addr
@get_l
@get_lvar_name
@get_mem
@get_mem_rel
@get_mem_rel_n
@ggparent
@globalise_procs_code
@globalise_procs_test
@globals_in_defn
@globals_to_pars_code
@globals_to_pars_test
@goto
@goto_body
@goto_defn
@goto_proc_body
@gp_globalisable_procs
@gparent
@grep_comps
@grow_symbol_table
@gt
@gtp_trim
@gtp_update_calls
@has_comps?
@has_comps_type?
@has_statements_type?
@has_value?
@has_value_type?
@hash_keys
@hex?
@hex_to_num
@hex_to_num_string
@hyb_tvs
@i
@i_eq
@i_eq_stats
@if_nest
@ifmatch_processing_code
@ifmatch_processing_test
@ifmatch_type?
@implies
@implies?
@in_hyb_system?
@in_hyb_system_gen?
@in_rec_system?
@in_rec_system_gen?
@in_reg_system?
@in_reg_system_gen?
@inc_hash
@increment
@increment_list
@increment_statement_code
@increment_statement_test
@incremented_equal?
@initialise
@initialise_adt
@insert_assertion_code
@insert_assertion_test
@insertion_sort
@invert
@invert_all
@invert_find_var
@invertible?
@ip_walk

@is_addr?
@is_dsect?
@is_dummy?
@is_enclosing_loops?
@is_entry_point?
@is_improper?
@is_in_var?
@is_mem?
@is_mem_rel?
@is_proper?
@is_reachable?
@is_reducible?
@is_terminal?
@is_terminal_posn?
@item
@join
@join_all_cases_code
@join_all_cases_test
@join_cases_left_code
@join_cases_left_test
@join_cases_right_code
@join_cases_right_test
@join_point?
@join_removing_dups
@last_non_comment
@lc_suffix
@left
@left?
@list_to_hash
@list_to_set
@list_to_string
@list_to_vector
@list_type?
@localise_procs_code
@localise_procs_test
@look_for_assertion
@loop_doubling_code
@loop_doubling_test
@loop_inversion_code
@loop_inversion_test
@loop_to_move_code
@loop_to_move_sub
@loop_to_move_sub2
@loop_to_move_test
@lower_case
@lp_add_defns
@lp_localisable_procs
@lr_equal?
@lr_seq_equal?
@lvalue_name
@lvalue_to_expn
@lvars
@make
@make_addr
@make_and_use_assertion
@make_assigns
@make_assoc
@make_bfunct
@make_funct
@make_get_n
@make_loop_code
@make_loop_test
@make_make
@make_mem
@make_mem_l
@make_mem_seg
@make_mem_seg_l
@make_mwf
@make_name
@make_proc
@make_proc_code
@make_proc_span
@make_proc_test
@make_reducible_code
@make_reducible_test
@make_set
@many_pattern_type?
@match
@match_to_fill
@match_vars
@max_depth
@max_pos_l
@may_term?
@mc_entry_actions
@mccabe
@mccabe_sub
@merge_calls
@merge_calls_in_action_code
@merge_calls_in_action_test
@merge_calls_in_cond
@merge_calls_in_system_code
@merge_calls_in_system_test
@merge_cond_right_code
@merge_cond_right_test
@merge_left_code
@merge_left_test
@merge_right_code
@merge_right_test
@meta_trans_code
@meta_trans_test
@move_assignment_left
@move_assignment_right
@move_comment_left_code
@move_comment_left_test
@move_comment_right_code
@move_comment_right_test
@move_comments_code
@move_comments_test
@move_to_left_code
@move_to_left_test
@move_to_right_code
@move_to_right_test
@mp_ensure_where
@mp_proc_calls
@mp_remove_z
@mr_bad_subexp?
@mr_make_and_absorb_proc

@mr_process
@mr_push_call_test
@mr_statements
@mt_replace
@mt_replace_st

@mt_sort_types
@mth_all_constants?
@mth_all_numbers?
@mth_bug_fix_concat
@mth_common_components
@mth_constant?
@mth_constants?
@mth_count_occs
@mth_de_morgan
@mth_de_morgan_not
@mth_duplicate_relations
@mth_duplicate_relations_sub

@mth_eval_exponent
@mth_evaluate
@mth_expand
@mth_expensive
@mth_factor
@mth_factorise
@mth_flatten
@mth_init
@mth_invert
@mth_known_value1
@mth_known_value2
@mth_known_value3
@mth_known_value4
@mth_lt?
@mth_merge
@mth_multiply
@mth_negate
@mth_occs
@mth_patterns
@mth_prettify
@mth_prettify_inverses

@mth_quantifiers
@mth_quantifiers_sub
@mth_replace
@mth_same_args
@mth_sequence
@mth_simplify_using
@mth_sort
@mth_sort_merge
@mth_sort_merge_item

@mth_subset?
@mth_subset_sub
@mth_swappable?
@mth_types
@mth_values
@mth_zeros?
@multi_calls
@n_length
@n_string
@name
@name_length
@name_or_num_string
@name_to_wsl
@name_value
@new_match
@new_match_list
@new_match_list_sub
@new_program
@new_tr_number
@new_yy_a_prefix_op
@next_stats
@no_trans_tests
@non_recursive_calls
@non_recursive_funct_calls
@not
@notice
@num_list
@num_to_hex
@one_int_type?
@one_pattern_type?
@one_var_type?
@only_calls_z?
@open_input_file
@open_output_file
@or
@original_program
@outermost_floop_terminal?
@parent
@parse_basic_blocks
@parse_del_file
@parse_file
@parse_num
@parse_nums
@parse_string
@parse_word
@parse_words
@partially_join_cases_code
@partially_join_cases_code_orig
@partially_join_cases_test
@pass
@passed?
@paste_after
@paste_before
@paste_before_nth
@paste_cond
@paste_over
@pat_add
@pat_rcl
@pat_sto
@pat_true
@pattern_to_make
@pattern_to_make2
@pd_check_dest_codes

@pd_check_dest_codes_assigns

@pd_check_dest_codes_orig

@peek_char
@pick
@pl
@pop_command
@posn
@posn_n
@powerset
@pp
@pp_1
@pp_1_line
@pp_calc
@pp_call

@pp_close

@pp_fill
@pp_find_pop
@pp_funct
@pp_indent
@pp_infix
@pp_item
@pp_join
@pp_n_lines
@pp_new_var
@pp_simple
@pp_size
@ppc_a_proc_call_os?
@prefix?
@prefix_equal?
@preserves_destination

@primed_vars
@print_ar
@print_assigns_sub
@print_basic_blocks
@print_elt
@print_elt_list
@print_elts
@print_name
@print_proc_summ2
@print_summ
@print_summ2
@print_wsl
@prit
@proc_call_freq
@proc_called?
@proc_calls
@proc_to_funct_code
@proc_to_funct_test
@proc_to_summ2
@prog_to_spec_code
@prog_to_spec_test
@program
@prpr
@prune_dispatch_code
@prune_dispatch_test
@ps
@push_pop_code
@push_pop_code_old
@push_pop_doit
@push_pop_test
@push_pop_test_old
@put_as_in_double_loop
@qry_add_index
@qry_add_index1
@qry_aref_elts
@qry_call_join
@qry_elts
@qry_exp_elts
@qry_exp_elts_a
@qry_exp_vars
@qry_exp_vars_a
@qry_get_lvar
@qry_get_lvar_elts
@qry_remove_a_call
@qry_simple_lstruct?
@qry_simple_struct?
@qry_vars
@quick_sort
@quick_sort2
@quick_sort3
@quick_sort4
@quick_sort5
@quick_sort_rec2
@quick_sort_rec3
@quick_sort_rec4
@quick_sort_rec5
@random
@rawv
@rc_restore_wheres
@reachable_calls
@read_char
@read_line
@read_line_proc
@read_options_file
@rec_tvs
@recursion_to_loop_code
@recursion_to_loop_test
@recursive?
@recursive_system?
@redefined
@redo
@redoable?
@reduce_loop_code
@reduce_loop_test
@reduce_multiple_loops_code
@reduce_multiple_loops_test
@refine_spec
@refine_spec_code
@refine_spec_sub1
@refine_spec_sub2
@refine_spec_sub3
@refine_spec_sub4
@refine_spec_test
@reg_tvs
@regular?
@regular_system?
@rel_seg
@remove_all_redundant_vars_code
@remove_all_redundant_vars_test
@remove_dummy_loop_code
@remove_dummy_loop_test
@remove_elementary
@remove_recursion

@remove_redundant_vars_code
@remove_redundant_vars_test
@rename
@rename_defns_code
@rename_defns_test
@rename_local_vars_code
@rename_local_vars_test
@rename_primed
@rename_proc_code
@rename_proc_test
@rename_procs

@replace
@replace_accs_with_value_code
@replace_accs_with_value_test
@replace_condition

@replace_nth
@replace_with_value_code
@replace_with_value_test
@replace_with_variable_code
@replace_with_variable_test
@reserved_word_error
@reset_pass_status
@restore_local_vars_code
@restore_local_vars_test
@restore_names
@restore_path_items
@reverse_order_code
@reverse_order_test
@right
@right?
@rlv_assign
@rlv_parse_var
@rlv_process
@roll_loop_code
@roll_loop_test
@rp_cond
@rp_count_proc_defns
@rp_expn
@rp_get_name
@rp_in_set_list?
@rp_item
@rp_lval
@rp_name
@rp_new_name
@rp_rename_procs
@rp_stat
@rp_trans
@rrv_code_funct
@rrv_code_var
@rrv_delete_refs
@rrv_filter_assigns
@rrv_funct_test
@rrv_maybe_expand
@rrv_proc_vars
@rrv_remove_refs
@rrv_rename
@rrv_simple
@rrv_sub_test
@rrv_top_level_redundant
@rrv_top_level_remove
@rs_filter
@runtime
@s2_add
@s2_apply
@s2_assigns
@s2_cond
@s2_cond_test
@s2_decrement
@s2_default
@s2_floop
@s2_for
@s2_get_proc_summary
@s2_increment
@s2_join
@s2_list_to_hash
@s2_loop
@s2_lvalues
@s2_maybe
@s2_maybe_sub
@s2_merge
@s2_merge_vars
@s2_prefix
@s2_prefix_list
@s2_proc_call
@s2_reachable
@s2_remove
@s2_rename
@s2_rename_sub
@s2_seq
@s2_seq_sub
@s2_seq_vars
@s2_sequence
@s2_summarise_body
@s2_summarise_body_sub
@s2_summarise_body_sub_orig
@s2_var
@s2_where
@s2_while
@s_add
@s_assert
@s_assert_condition
@s_assigns
@s_check_pair
@s_cond
@s_cond_test
@s_decrement
@s_default
@s_deny_condition
@s_floop
@s_for
@s_get_proc_summary
@s_increment
@s_loop
@s_loop_old
@s_merge
@s_merge_vars
@s_move_assign_vars
@s_ok?
@s_proc_call
@s_put_proc_summary

@s_remove
@s_rename
@s_rename_sub
@s_seq
@s_seq_sub
@s_seq_vars
@s_sequence
@s_summarise_body
@s_summarise_body_sub
@s_var
@s_where
@s_while
@sas_as_type
@sas_call_freq
@sas_calls_terminal?
@sas_expand_calls_in_body

@sas_new_call_freq
@sas_reachable_calls
@sas_replace_elem_action_calls

@sas_succs_and_preds

@sas_take_out_dup_calls
@sas_unfold_once_called
@sas_update_call_freq
@save_command
@save_state
@sec_simple
@sec_simple?
@sec_split
@seed_random_state
@semantic_slice_code
@semantic_slice_sub

@semantic_slice_test
@separate_both_code
@separate_both_test
@separate_exit_code_code
@separate_exit_code_sub
@separate_exit_code_test
@separate_left_code
@separate_left_test
@separate_right_code
@separate_right_test
@seq_equal?
@set_budget
@set_difference
@set_intersect
@set_subset?
@set_union
@shell_sort
@si_special
@si_special?
@si_special_guard?
@si_stats_to_expn
@simple?
@simple_slice_code
@simple_slice_test
@simple_var_assigns?
@simplify
@simplify_action_system_code
@simplify_action_system_test
@simplify_bfunct_calls
@simplify_bit
@simplify_bit_ops
@simplify_code
@simplify_cond
@simplify_expn
@simplify_if_code
@simplify_if_loop?
@simplify_if_test
@simplify_if_using
@simplify_if_using?
@simplify_item_code
@simplify_item_test
@simplify_test
@simplify_using
@size
@skip
@skip?
@skip_spaces
@skips
@slice
@slice_orig
@smallest_call
@sort_less?
@sort_list
@sort_merge
@sort_merge_num
@sort_num
@sort_procs_code
@sort_procs_test
@sort_test
@sort_test_list
@sp_dfs_calls
@span
@spec_type
@spec_type_count
@spec_types
@speculative_entire_unrolling

@speculative_unrolling

@splice_after
@splice_before
@splice_before_nth
@splice_nth
@splice_over
@split
@split_on
@split_preprocess

@sr_assignment_test
@sr_floop
@sr_floop_test

@srt_find_stack
@ss_delete
@ss_filter
@ss_keep
@ssa_convert_elt
@ssa_fix_a_proc_call
@ssa_make_name
@ssa_make_phi
@ssa_orig_elt
@ssa_orig_name
@ssa_orig_var
@ssa_phi_insert

@ssa_rename

@sslice
@st
@stack_to_par_code
@stack_to_par_test
@stack_to_return_code
@stack_to_return_test
@stack_to_var_code
@stack_to_var_test
@star_match_type?
@star_patterns?
@starts_with?
@starts_with_plus_num?
@stat_count
@stat_count_nc
@stat_types
@static_single_assignment_code
@static_single_assignment_test
@str_make_local
@str_match?
@string
@string_to_list
@string_to_num
@strip_char
@struct_elts
@struct_elts_old
@struct_metric
@struct_to_string
@sub_seg
@substitute_and_delete_code
@substitute_and_delete_list_code
@substitute_and_delete_list_test
@substitute_and_delete_test
@substitute_once_called

@substitute_parameter_values
@summ2
@summ2_list
@summ2_to_wsl
@summ2_to_wsl_sub
@summ2_where_defns
@summ_to_wsl
@summ_to_wsl_sub
@summarise
@summarise_where_defns
@swap_assigns
@swap_case
@swap_expn
@syntactic_slice_code
@syntactic_slice_test
@syntax
@syntax_error
@syntax_ok?
@system_type
@system_type_gen
@tail_recursive?
@take_out_left_code
@take_out_left_test
@take_out_left_test_floop
@take_out_left_test_for
@take_out_left_test_guarded
@take_out_left_test_var
@take_out_left_test_where
@take_out_left_test_while
@take_out_of_loop_code
@take_out_of_loop_test
@take_out_of_loop_test2
@take_out_right_code
@take_out_right_test
@take_out_right_test_for
@take_out_right_test_guarded
@take_out_right_test_var
@take_out_right_test_where
@take_out_right_test_while
@terminal_n?
@terminal_posn?
@test_maths
@test_trans

@to
@to_last
@tol_add_incs

@tol_check_list

@tol_check_loop

@tol_count_loops

@tol_max_tv
@tol_min_tv
@tol_normalise
@topological_sort

@total_size
@trans
@trans?
@trans_tests_status?
@transitive_closure
@transitive_closure_new
@transitive_closure_simple
@trim_extra_pars
@trim_underscore_number
@trim_wsl_from_ssa
@true?
@tv_conditional_union
@tvs
@type_name
@ua_process
@ua_while
@uba
@undo
@undo_edit
@undoable?
@unfold_proc_call
@unfold_proc_call_code
@unfold_proc_call_test
@unfold_proc_calls_code
@unfold_proc_calls_test
@unroll_loop_code
@unroll_loop_test
@unsafe_test?
@up
@up?
@up_to_loop
@up_to_statement
@upc_unfold
@update_segment
@upper_case
@use_assertion_code
@use_assertion_test
@use_trans_tests
@used
@used_only
@v
@v1
@valid_posn?
@value
@value_length
@value_string
@var_pars_to_val_pars_code
@var_pars_to_val_pars_test
@var_to_expn
@var_to_expn_list
@var_to_expn_type
@variables
@warning
@wc_numeric_exp?
@wf_fix
@what_trans
@while_to_abort_code
@while_to_abort_test
@while_to_abort_test2
@while_to_floop_code
@while_to_floop_test
@while_to_for_in_code
@while_to_for_in_test
@while_to_reduce_code
@while_to_reduce_test
@will_term?
@wl
@wn
@word_in_string?
@wp
@wr_reduce_par2

@wr_reduce_pars
@write
@write_cg_line
@write_line
@write_raw_item
@write_summ2
@write_to
@ws
@ws_assign
@ws_calls?
@ws_constant_fill?
@ws_decl
@ws_fill
@ws_funct_decl

@ws_ifmatch
@ws_item
@ws_items
@ws_name
@ws_par
@ws_replace
@ws_seg
@ws_special
@ws_value_to_make
@ws_var_block
@wsl_to_scheme
@wsl_to_ssa
@wss
@wssl
@x_funct_call_freq
@x_funct_called?
@x_funct_calls
@yy_a_expression
@yy_a_prefix_op
@yy_action
@yy_actions
@yy_aproc_call
@yy_array
@yy_array_ref
@yy_as
@yy_assert
@yy_assign
@yy_assign_pattern
@yy_assignment
@yy_assigns
@yy_at_name
@yy_ateach
@yy_b_atom
@yy_b_factor
@yy_b_term
@yy_bfunct
@yy_bfunct_call
@yy_build_a_expr
@yy_build_s_expr
@yy_call
@yy_check_end
@yy_checkfor_aref
@yy_comment
@yy_cond_pattern
@yy_condition
@yy_crank
@yy_d_generic
@yy_define
@yy_defines
@yy_defn_pattern
@yy_error
@yy_exit
@yy_exp_atom
@yy_exp_pattern
@yy_expression
@yy_expressions
@yy_external_call
@yy_f_assigns
@yy_factor
@yy_fill
@yy_fill_s
@yy_floop
@yy_for
@yy_foreach
@yy_forin
@yy_funct
@yy_funct_call
@yy_gen_exp_atom
@yy_gen_prefix_op
@yy_gen_print
@yy_generic_proc
@yy_guard_gen
@yy_guarded
@yy_guarded_pattern
@yy_ident
@yy_if
@yy_if_expression
@yy_ifmatch
@yy_ifmatch_body
@yy_ifmatch_s
@yy_infix_op
@yy_join
@yy_lex
@yy_lex_debug
@yy_look
@yy_lv_array_check
@yy_lv_array_ref
@yy_lv_mem_ref
@yy_lv_struct_ref
@yy_lvalue
@yy_lvalues
@yy_maphash
@yy_mem_ref
@yy_mw_bfunct
@yy_mw_bfunct_call
@yy_mw_call
@yy_mw_funct
@yy_mw_funct_call
@yy_mw_name
@yy_mw_proc
@yy_mw_proc_call
@yy_name
@yy_next
@yy_number
@yy_old_print
@yy_parse
@yy_parse_pattern
@yy_pattern
@yy_pc_binary
@yy_pc_forall
@yy_pc_unary
@yy_peek
@yy_pop
@yy_prefix_cond
@yy_print
@yy_proc
@yy_proc_arg_list
@yy_proc_call
@yy_push
@yy_rest_of_cond
@yy_s_atom
@yy_s_expression
@yy_s_factor
@yy_s_term
@yy_sequence
@yy_set
@yy_single_assign
@yy_skip_symbol
@yy_spec
@yy_sr_cond_engine
@yy_sr_parse_cond
@yy_stat_pattern
@yy_statement
@yy_statements
@yy_string
@yy_struct_ref
@yy_term
@yy_trivial
@yy_true_factor
@yy_var
@yy_where
@yy_while
@yy_x_bfunct_call
@yy_x_funct_call
@yy_x_proc_call
@zero_tv_count
alist-remove
asso
build-vector
butlast-1
byte-ref
byte-set!
char-swapcase
concat
firstn
frac
gethash
gethash-1
hash:hash
hash:hash-char
hash:hash-number
hash:hash-string
hash:hash-symbol
int
last-1
logical:ash
logical:ash-4
logical:bit-field
logical:integer-length
logical:ipow-by-squaring
logical:logand
make-bytes
make-null-list
my-make-hash-table
my-string-downcase
my-string-index
my-string-upcase
myrandom
nthcdr
perlscript
puthash
random:chunk
remhash
replace-nth
seed->random-state
sequence?
sgn
str-downcase!
str-swapcase!
str-upcase!
string-swapcase
substring?
user-interrupt
vector-elts
)))
